// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('backButtonTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('backButtonTest', async function() {
    await driver.get("https://qa.medcloud.link/careers.html")
    await driver.manage().window().setRect({ width: 2576, height: 1066 })
    await driver.findElement(By.linkText("Voltar ao site")).click()
    assert(await driver.getTitle() == "Medcloud – PACS, RIS, Patient Portal and Storage")
  })
})
