// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('languageChangeTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('languageChangeTest', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.manage().window().setRect({ width: 2560, height: 1050 })
    await driver.findElement(By.css(".float-right:nth-child(3)")).click()
    assert(await driver.findElement(By.css(".sm\\3Aw-full:nth-child(3) > .text-base")).getText() == "About Medcloud")
    await driver.close()
  })
})
