// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('spotifyLinkTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('spotifyLinkTest', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.manage().window().setRect({ width: 2560, height: 1050 })
    await driver.findElement(By.css(".space-x-6 > a:nth-child(1)")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    assert(await driver.getTitle() == "Momento Saúde Digital | Podcast on Spotify")
    await driver.close()
  })
})
