// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('twitterLinkTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('twitterLinkTest', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.manage().window().setRect({ width: 2560, height: 1050 })
    await driver.findElement(By.css("a:nth-child(4)")).click()
    assert(await driver.getTitle() == "Medcloud (@Medcloudbr) / Twitter")
    await driver.close()
  })
})
